// <auto-generated />
namespace Library.DOMAIN.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _add_abstract : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_add_abstract));
        
        string IMigrationMetadata.Id
        {
            get { return "201610081742209__add_abstract"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
