// <auto-generated />
namespace Library.DOMAIN.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class MUST_BE_DELETED3 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(MUST_BE_DELETED3));
        
        string IMigrationMetadata.Id
        {
            get { return "201610091336536_MUST_BE_DELETED3"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
