// <auto-generated />
namespace Library.DOMAIN.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class books_add_publisher : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(books_add_publisher));
        
        string IMigrationMetadata.Id
        {
            get { return "201610011900349_books_add_publisher"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
