// <auto-generated />
namespace Library.DOMAIN.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _tuesday_ : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_tuesday_));
        
        string IMigrationMetadata.Id
        {
            get { return "201609201028501__tuesday_"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
